services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: fumblefunds-db
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - fumblefunds-net

  api:
    build:
      context: ./src/FumbleFunds.Api
      dockerfile: DockerFile
    container_name: fumblefunds-api
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;User Id=${SA_USER};Password=${SA_PASSWORD};Database=FumbleFundsDb;TrustServerCertificate=True;
    depends_on:
      - db
    ports:
      - "5000:80"
    networks:
      - fumblefunds-net

volumes:
  dbdata:

networks:
  fumblefunds-net:
    driver: bridge
